In [120]:
import numpy as np
from osgeo import ogr, gdal
import rasterio
import json

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os.path
import re

from osgeo import gdal
from osgeo import gdal_array
from osgeo import osr

In [121]:
area_cover = '/home/shrayank_mistry/Modules/Area-routes/PanvelD/mask.tif'
area = rasterio.open(area_cover, count = 1)

area = np.array(area.read(1))

In [122]:
area_dem = '/home/shrayank_mistry/Modules/Area-routes/PanvelD/dem_clipped.tif'
dem = rasterio.open(area_dem, count = 1)

dem = np.array(dem.read(1))
print(dem.shape)

(6850, 3787)


In [123]:
import rasterio
from rasterio.enums import Resampling

# whole-numbers indicate upscaling, fractions indicate downscaling
upscale_factor = 3


with rasterio.open('/home/shrayank_mistry/Modules/Area-routes/PanvelD/dem_clipped.tif') as dataset:

    # resample data to target shape
    data = dataset.read(
        out_shape=(
            dataset.count,
            int(dataset.height * upscale_factor),
            int(dataset.width * upscale_factor)
        ),
        resampling=Resampling.bilinear
    )

    # scale image transform
    transform = dataset.transform * dataset.transform.scale(
        (dataset.width / data.shape[-1]),
        (dataset.height / data.shape[-2])
    )

In [124]:
area = np.swapaxes(area, 1, 0)
print(area.shape)

up_dem = data[0]
up_dem.shape

(10980, 20976)


(20550, 11361)

In [125]:
dem_data, mask_data = up_dem, area
dem_data = dem_data.T


print(dem_data.shape, mask_data.shape)
width, height = 10980, 20550

dem_data, mask_data = dem_data[:width,:height], mask_data[:width, :height]
print(dem_data.shape, mask_data.shape)

(11361, 20550) (10980, 20976)
(10980, 20550) (10980, 20550)


In [126]:
ahp_map = {

'urban': 0.29,
'farms': 0.239,
'dense-forest': 0.207,
'water': 0.13,
'fallow': 0.067,
'sparse-forest': 0.049,
'barren-land': 0.019,
'unclassified':7,

}

class_map = {

    0: 'unclassified',
    1: 'water',
    2: 'dense-forest',
    3: 'sparse-forest',
    4: 'barren-land',
    5: 'urban',
    6: 'farms',
    7: 'fallow',
    
}

In [127]:
from copy import deepcopy
mask_copy = deepcopy(mask_data)

In [128]:
np.unique(mask_copy, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16),
 array([     6905,  13089183,   7310198,  38895518, 102339438,  10359278,
         13921633,  39716847]))

In [129]:
def set_weights(c):
    c_str = class_map.get(c)
    return ahp_map[c_str]

In [130]:
# for i in range(mask_data.shape[0]):
#     for j in range(mask_data.shape[1]):

#         mask_copy[i][j] = set_weights(mask_data[i][j])

In [131]:
set_weights_vtr = np.vectorize(set_weights, otypes=[np.float])
mask_copy = set_weights_vtr(mask_data)

In [132]:
np.unique(mask_copy, return_counts = True)

(array([0.019, 0.049, 0.067, 0.13 , 0.207, 0.239, 0.29 , 7.   ]),
 array([102339438,  38895518,  39716847,  13089183,   7310198,  13921633,
         10359278,      6905]))

In [133]:
np.unique(mask_data, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16),
 array([     6905,  13089183,   7310198,  38895518, 102339438,  10359278,
         13921633,  39716847]))

In [134]:
from osgeo import ogr
import json

file = ogr.Open("/home/shrayank_mistry/Modules/Area-routes/PanvelD/source/source.shp")
source_shp = file.GetLayer(0)

feature = source_shp.GetFeature(0)
source_shp = feature.ExportToJson()

# source_shp
source_shp = json.loads(source_shp)
start_ext = source_shp['geometry']['coordinates']

In [135]:
file = ogr.Open("/home/shrayank_mistry/Modules/Area-routes/PanvelD/destination/destination.shp")
destination_shp = file.GetLayer(0)

feature = destination_shp.GetFeature(0)
destination_shp = feature.ExportToJson()

destination_shp

# source_shp
destination_shp = json.loads(destination_shp)
end_ext = destination_shp['geometry']['coordinates']

In [136]:
print(start_ext, end_ext)

[306666.8831168013, 2098263.628266526] [304717.23743578803, 1941342.757008533]


In [137]:
from osgeo import ogr, gdal
import os
import subprocess
import rasterio

In [138]:
path = '/home/shrayank_mistry/Modules/Area-routes/PanvelD/raster.tif' 

data = rasterio.open(path)
print(data.bounds)

extent = data.bounds

left, bottom, right, top = extent[0], extent[1], extent[2], extent[3]
print(left, bottom, right, top)

BoundingBox(left=300000.0, bottom=1890240.0, right=409800.0, top=2100000.0)
300000.0 1890240.0 409800.0 2100000.0


In [139]:
width = round(right - left)
height = round(top - bottom)

print("Width and Height of Raster")
print(width, height)

Width and Height of Raster
109800 209760


In [140]:
# width = round(right - left)
# height = round(top - bottom)

# print(width, height)

# start_pixel, end_pixel = [0, 0], [0, 0]
# start_flag, end_flag = True, True

# for i in range(height):
#     for j in range(width):

#         if (not start_flag) and (not end_flag):
#             break
        
#         # print(round(left + j), round(top - i))
#         if (start_flag and ((round(left + j)) == round(start_ext[0])) and ((round(top - i)) == round(start_ext[1]))):
#             start_pixel = [i, j]
#             start_flag = False

        
#         if (end_flag and ((round(left + j)) == round(end_ext[0])) and ((round(top - i)) == round(end_ext[1]))):
#             end_pixel = [i, j]
#             end_flag = False

In [141]:
# start_pixel, end_pixel

In [142]:
# start_pixel, end_pixel = [15293, 84135], [126987, 41253]
# start_pixel, end_pixel = [84135, 15293], [41253, 126987]
start_pixel, end_pixel = [1736, 6667], [158657, 4717]

In [143]:
start_pixel = np.array(start_pixel)
start_pixel = start_pixel / 10

start_pixel = list(np.rint(start_pixel))
start_pixel = list(np.array(start_pixel, dtype = 'int'))

end_pixel = np.array(end_pixel)
end_pixel = end_pixel / 10

end_pixel = list(np.rint(end_pixel))
end_pixel = list(np.array(end_pixel, dtype = 'int'))

### Dijkstra's Algorithm for Anistropic Accumulated-Cost Calculation

In [144]:
def condition_check(start, end):
    if (start[0] == end[0]) and (start[1] == end[1]):
        return False
    return True

In [145]:
import math
from queue import PriorityQueue

In [146]:
from copy import deepcopy
mask_copy_t = deepcopy(mask_copy)

In [147]:
mask_copy = mask_copy * 5000

In [148]:
# mask_copy = mask_copy.T
# print(mask_copy.shape)

# dem_data = dem_data.T
# print(dem_data.shape)

In [149]:
np.unique(mask_copy, return_counts = True)

(array([   95.,   245.,   335.,   650.,  1035.,  1195.,  1450., 35000.]),
 array([102339438,  38895518,  39716847,  13089183,   7310198,  13921633,
         10359278,      6905]))

In [150]:
def c_anist_cost(i, j, x, y, mu = 10, wt = 2):

    mu_sqr = mu * mu
    h_diff = dem_data[i][j] - dem_data[x][y]
    h_sqr = h_diff * h_diff
    c_dv = (mask_copy[i][j] + mask_copy[x][y]) / 2
    cst = np.sqrt(mu_sqr + h_sqr) * (c_dv + math.atan(h_diff / mu) * wt) + acc_cost[i][j]

    # print(cst)
    return cst


In [151]:
def get_neigh_cost(i, j, lt_iw, lt_jh):
    arr = []
    #(1) col - 1, row - 1
    if (j - 1 >= 0) and (i - 1 >= 0):
        # arr.append([c_anist_cost(i, j, i - 1, j - 1), [i - 1, j - 1], [i, j]])
        # acc_cost[i - 1][j - 1] = min(c_anist_cost(i, j, i - 1, j - 1), acc_cost[i - 1][j - 1])

        if (acc_cost[i - 1][j - 1] > c_anist_cost(i, j, i - 1, j - 1)):
            parent[i - 1][j - 1] = i, j
            acc_cost[i - 1][j - 1] = c_anist_cost(i, j, i - 1, j - 1)
        arr.append([acc_cost[i - 1][j - 1], [i - 1, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(2) col, row - 1
    if (i - 1 >= 0):
        # arr.append([c_anist_cost(i, j, i - 1, j), [i - 1, j], [i, j]])
        # acc_cost[i - 1][j] = min(c_anist_cost(i, j, i - 1, j), acc_cost[i - 1][j])

        if (acc_cost[i - 1][j] > c_anist_cost(i, j, i - 1, j)):
            parent[i - 1][j] = i, j
            acc_cost[i - 1][j] = c_anist_cost(i, j, i - 1, j)
        arr.append([acc_cost[i - 1][j], [i - 1, j], [i, j]])
    else:
        arr.append(math.inf)

    #(3) col + 1, row - 1
    if (j + 1 < lt_jh) and (i - 1 >= 0):
        # arr.append([c_anist_cost(i, j, i - 1, j + 1), [i - 1, j + 1], [i, j]])
        # acc_cost[i - 1][j + 1] = min(c_anist_cost(i, j, i - 1, j + 1), acc_cost[i - 1][j + 1])

        if (acc_cost[i - 1][j + 1] > c_anist_cost(i, j, i - 1, j + 1)):
            parent[i - 1][j + 1] = i, j
            acc_cost[i - 1][j + 1] = c_anist_cost(i, j, i - 1, j + 1)
        arr.append([acc_cost[i - 1][j + 1], [i - 1, j + 1], [i, j]])
    else:
        arr.append(math.inf)

    #(4) col - 1, row
    if (j - 1 >= 0):
        # arr.append([c_anist_cost(i, j, i, j - 1), [i, j - 1], [i, j]])
        # acc_cost[i][j - 1] = min(c_anist_cost(i, j, i, j - 1), acc_cost[i][j - 1])

        if (acc_cost[i][j - 1] > c_anist_cost(i, j, i, j - 1)):
            parent[i][j - 1] = i, j
            acc_cost[i][j - 1] = c_anist_cost(i, j, i, j - 1)
        arr.append([acc_cost[i][j - 1], [i, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(5) col + 1, row
    if (j + 1 < lt_jh):
        # arr.append([c_anist_cost(i, j, i, j + 1), [i, j + 1], [i, j]])
        # acc_cost[i][j + 1] = min(c_anist_cost(i, j, i, j + 1), acc_cost[i][j + 1])

        if (acc_cost[i][j + 1] > c_anist_cost(i, j, i, j + 1)):
            parent[i][j + 1] = i, j
            acc_cost[i][j + 1] = c_anist_cost(i, j, i, j + 1)
        arr.append([acc_cost[i][j + 1], [i, j + 1], [i, j]])
    else:
        arr.append(math.inf)

    #(6) col - 1, row + 1
    if (j - 1 >= 0) and (i + 1 < lt_ih):
        # arr.append([c_anist_cost(i, j, i + 1, j - 1), [i + 1, j - 1], [i, j]])
        # acc_cost[i + 1][j - 1] = min(c_anist_cost(i, j, i + 1, j - 1), acc_cost[i + 1][j - 1])

        if (acc_cost[i + 1][j - 1] > c_anist_cost(i, j, i + 1, j - 1)):
            parent[i + 1][j - 1] = i, j
            acc_cost[i + 1][j - 1] = c_anist_cost(i, j, i + 1, j - 1)
        arr.append([acc_cost[i + 1][j - 1], [i + 1, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(7) col, row + 1
    if (i + 1 < lt_ih):
        # arr.append([c_anist_cost(i, j, i + 1, j), [i + 1, j], [i, j]])
        # acc_cost[i + 1][j] = min(c_anist_cost(i, j, i + 1, j), acc_cost[i + 1][j])

        if (acc_cost[i + 1][j] > c_anist_cost(i, j, i + 1, j)):
            parent[i + 1][j] = i, j
            acc_cost[i + 1][j] = c_anist_cost(i, j, i + 1, j)
        arr.append([acc_cost[i + 1][j], [i + 1, j], [i, j]])
    else:
        arr.append(math.inf)

    #(8) col + 1, row + 1
    if (j + 1 < lt_jh) and (i + 1 < lt_ih):
        # arr.append([c_anist_cost(i, j, i + 1, j + 1), [i + 1, j + 1], [i, j]])
        # acc_cost[i + 1][j + 1] = min(c_anist_cost(i, j, i + 1, j + 1), acc_cost[i + 1][j + 1])

        if (acc_cost[i + 1][j + 1] > c_anist_cost(i, j, i + 1, j + 1)):
            parent[i + 1][j + 1] = i, j
            acc_cost[i + 1][j + 1] = c_anist_cost(i, j, i + 1, j + 1)
        arr.append([acc_cost[i + 1][j + 1], [i + 1, j + 1], [i, j]])
    else:
        arr.append(math.inf)
    

    return arr

In [152]:
# start_pixel, end_pixel = [1770, 1442], [8344, 5485]
start_pixel, end_pixel = [174, 667], [15866, 472]
print(start_pixel, end_pixel)

[174, 667] [15866, 472]


In [153]:
dim = mask_copy.shape
print(dim)

(10980, 20550)


In [154]:
print(mask_copy.shape, dem_data.shape)

(10980, 20550) (10980, 20550)


In [155]:
visited = np.zeros((dim))
acc_cost = np.full((dim), math.inf)

print(visited.shape, acc_cost.shape)

(10980, 20550) (10980, 20550)


In [156]:
print(start_pixel, end_pixel)

[174, 667] [15866, 472]


In [157]:
# start_pixel, end_pixel = [174, 667], [15866, 472]
# start_pixel, end_pixel = [667, 174], [472, 15866]
start_pixel, end_pixel = [667, 174], [550, 209]
print(start_pixel, end_pixel)

[667, 174] [550, 209]


In [158]:
print(width, height)

109800 209760


In [159]:
wd, ht = int(width / 10), int(height / 10)
print(wd, ht)

10980 20976


In [160]:
last_pixel = None

In [161]:
Q = PriorityQueue()

# Width and Height Limit of area
lt_ih, lt_jh = wd, ht
s_pixel, e_pixel = start_pixel, end_pixel

# mask_copy.shape, dem_data.shape

visited = np.zeros((dim))
acc_cost = np.full((dim), math.inf)

acc_cost[s_pixel[0]][s_pixel[1]] = 0
visited[s_pixel[0]][s_pixel[1]] = 1

parent = np.full((dim), None)
parent[s_pixel[0]][s_pixel[1]] = -1, -1


path = list()

while (condition_check(s_pixel, e_pixel)):
    # print('in')
    i, j = s_pixel
    # print(i, j)

    neighbours_cost = get_neigh_cost(i, j, lt_ih, lt_jh)
    for nc in neighbours_cost:
        if nc == math.inf:
            continue
        else:
            Q.put(nc)
    
    # check if current-best is visited OR not
    bst = Q.get()
    m, n = bst[1][0], bst[1][1]

    while True:
        if visited[m][n] == 0:
            break
        bst = Q.get()
        m, n = bst[1][0], bst[1][1]

    # set-visited
    visited[m][n] = 1
    path.append([m, n])
    # print(m, n)

    parent[m][n] = bst[2][0], bst[2][1]

    s_pixel = [m, n]
    last_pixel = s_pixel

In [162]:
# end_pixel = last_pixel

In [108]:
print(acc_cost[end_pixel[0]][end_pixel[1]])

155248.26352495863


In [109]:
!rm -rf path.txt

In [110]:
path = []
pr = parent[end_pixel[0]][end_pixel[1]]

# cnt = 15000
while (pr[0] != -1) and (pr[1] != -1):
    path.append(pr)
    # path.append('-')
    with open('/home/shrayank_mistry/Modules/Area-routes/PanvelD/routes-shape/dijk-route/path.txt', 'a') as f:
        f.write(str(pr) + '\n')

    # cnt = cnt - 1
    # if cnt == 0:
    #     break

    pr = parent[pr[0]][pr[1]]

In [111]:
path_list = []
with open('/home/shrayank_mistry/Modules/Area-routes/PanvelD/routes-shape/dijk-route/path.txt', 'r') as f:
    for point in f:
        path_list.append(point)

In [112]:
len(path_list)

208

In [113]:
point = path_list[0].replace('\n', '').split(' ')
pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])
print(pi, pj)

551 208


In [114]:
path_list.reverse()

In [115]:
%%time
ordinates_dict = {}


for i in range(len(path_list)):
    point = path_list[i].replace('\n', '').split(' ')
    pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])

    ext_i, ext_j = left + (pi * 10), top - (pj * 10)

    # ordinates_dict[(pi, pj)] = extent_matrix[pi][pj]
    ordinates_dict[pi, pj] = [ext_i, ext_j]

CPU times: user 439 µs, sys: 0 ns, total: 439 µs
Wall time: 442 µs


In [116]:
ordinates_dict
ordinates_list = []
for key, value in ordinates_dict.items():
    ordinates_list.append(value)

In [117]:
import shapefile
w = shapefile.Writer('/home/shrayank_mistry/Modules/Area-routes/PanvelD/routes-shape/dijk-route/shapefiles/test/multipoint')
w.field('name', 'C')

w.multipoint(ordinates_list) 
w.record('multipoint1')

w.close()

In [118]:
road_lenght = 0
index = 1
for _ in ordinates_list[1:]:
    i, j = ordinates_list[index][0], ordinates_list[index][1]
    x, y = ordinates_list[index - 1][0], ordinates_list[index - 1][1]

    if (x - i == 10.0) and (y - j == -10.0):
        road_lenght += math.sqrt(2 * 100)
    else:
        road_lenght += 10 

In [119]:
print(f'Current Road-length = {road_lenght / 1000} kms')

Current Road-length = 2.07 kms
