In [1]:
import numpy as np
from osgeo import ogr, gdal, osr
import rasterio
import json


import matplotlib.pyplot as plt
import pandas as pd
import os.path
import re
import math

#### Resize DEM from 30 to 10m

In [2]:
# Reading Normal DEM data
area_dem = '/home/shrayank_mistry/Modules/project-mum-pune/dem_clipped.tif'
dem = rasterio.open(area_dem, count = 1)

dem = np.array(dem.read(1))
print(dem.shape)

(2721, 3610)


In [3]:
# Up-sampling DEM to 10m resolution
import rasterio
from rasterio.enums import Resampling

# whole-numbers indicate upscaling, fractions indicate downscaling
upscale_factor = 3


with rasterio.open('/home/shrayank_mistry/Modules/project-mum-pune/dem_clipped.tif') as dataset:

    # resample data to target shape
    data = dataset.read(
        out_shape=(
            dataset.count,
            int(dataset.height * upscale_factor),
            int(dataset.width * upscale_factor)
        ),
        resampling=Resampling.bilinear
    )

    # scale image transform
    transform = dataset.transform * dataset.transform.scale(
        (dataset.width / data.shape[-1]),
        (dataset.height / data.shape[-2])
    )

In [4]:
dem = data[0]
print(dem.shape)

(8163, 10830)


In [5]:
# reading LULC data
area_cover = '/home/shrayank_mistry/Modules/project-mum-pune/mask.tif'
area = rasterio.open(area_cover, count = 1)

area = np.array(area.read(1))

In [6]:
dem_data, mask_data = dem, area

print(dem_data.shape, mask_data.shape)
width, height = 10500, 8163

dem_data, mask_data = dem_data[:height,:width], mask_data[:height, :width]
print(dem_data.shape, mask_data.shape)

dem_data, mask_data = dem_data.T, mask_data.T
print(dem_data.shape, mask_data.shape)

(8163, 10830) (8273, 10500)
(8163, 10500) (8163, 10500)
(10500, 8163) (10500, 8163)


#### AHP Mapping

In [7]:
ahp_map = {

'urban': 0.29,
'farms': 0.239,
'dense-forest': 0.207,
'water': 0.13,
'fallow': 0.067,
'sparse-forest': 0.049,
'barren-land': 0.019,
'unclassified':7,

}

class_map = {

    0: 'unclassified',
    1: 'water',
    2: 'dense-forest',
    3: 'sparse-forest',
    4: 'barren-land',
    5: 'urban',
    6: 'farms',
    7: 'fallow',

}

In [8]:
# Helper function to map from LULC to class-map to ahp values
def set_weights(c):
    c_str = class_map.get(c)
    return ahp_map[c_str]

In [9]:
set_weights_vtr = np.vectorize(set_weights)
mask_data = set_weights_vtr(mask_data)

In [10]:
np.unique(mask_data, return_counts = True)

(array([0.019, 0.049, 0.067, 0.13 , 0.207, 0.239, 0.29 , 7.   ]),
 array([19822048, 17097029, 28893954,  7807154,  3858436,  5940554,
         2291737,      588]))

#### Start-End Co-ordinates

In [11]:
# ----------------------------- source_shp -------------------------------- #

file = ogr.Open("/home/shrayank_mistry/Modules/project-mum-pune/route-files/source-point.shp")
source_shp = file.GetLayer(0)

feature = source_shp.GetFeature(0)
source_shp = feature.ExportToJson()

source_shp = json.loads(source_shp)
start_ext = source_shp['geometry']['coordinates']

# ----------------------------- destination_shp -------------------------------- #

file = ogr.Open("/home/shrayank_mistry/Modules/project-mum-pune/route-files/destination-point.shp")
destination_shp = file.GetLayer(0)

feature = destination_shp.GetFeature(0)
destination_shp = feature.ExportToJson()

destination_shp = json.loads(destination_shp)
end_ext = destination_shp['geometry']['coordinates']

In [12]:
print(start_ext, end_ext) 

[300378.7763074944, 2104126.3099621385] [366123.3883685307, 2063699.8154670105]


#### Raster Co-ordinates (Left, Bottom, Right, Top)

In [13]:
path = '/home/shrayank_mistry/Modules/project-mum-pune/raster.tif' 

data = rasterio.open(path)
print(data.bounds)

extent = data.bounds

left, bottom, right, top = extent[0], extent[1], extent[2], extent[3]
print(left, bottom, right, top)

BoundingBox(left=282680.0, bottom=2035820.0, right=387680.0, top=2118550.0)
282680.0 2035820.0 387680.0 2118550.0


In [14]:
width = round(right - left)
height = round(top - bottom)

print("Height and Width of Raster")
print(height, width)

Height and Width of Raster
82730 105000


### Finding pixels of start-point and end-point from extents

In [15]:
# [Do not run - already avaliable]
# start_pixel, end_pixel = [14424, 17699], [54850, 83443]
# start_pixel, end_pixel = [0, 0], [0, 0]
# start_flag, end_flag = True, True

# for i in range(height):
#     for j in range(width):

#         if (not start_flag) and (not end_flag):
#             break
        
#         # print(round(left + j), round(top - i))
#         if (start_flag and ((round(left + j)) == round(start_ext[0])) and ((round(top - i)) == round(start_ext[1]))):
#             start_pixel = [i, j]
#             start_flag = False

        
#         if (end_flag and ((round(left + j)) == round(end_ext[0])) and ((round(top - i)) == round(end_ext[1]))):
#             end_pixel = [i, j]
#             end_flag = False

In [16]:
start_pixel, end_pixel = [14424, 17699], [54850, 83443]

In [17]:
start_pixel = np.array(start_pixel)
start_pixel = start_pixel / 10

start_pixel = list(np.rint(start_pixel))
start_pixel = list(np.array(start_pixel, dtype = 'int'))

end_pixel = np.array(end_pixel)
end_pixel = end_pixel / 10

end_pixel = list(np.rint(end_pixel))
end_pixel = list(np.array(end_pixel, dtype = 'int'))

In [18]:
print(start_pixel, end_pixel)
start_pixel, end_pixel = [1770, 1442], [8344, 5485]
print(start_pixel, end_pixel)

[1442, 1770] [5485, 8344]
[1770, 1442] [8344, 5485]


#### Shortest Path Faster Algorithm (SPF)

In [19]:
mask_data = mask_data * 2000

In [20]:
np.unique(mask_data, return_counts = True)

(array([   38.,    98.,   134.,   260.,   414.,   478.,   580., 14000.]),
 array([19822048, 17097029, 28893954,  7807154,  3858436,  5940554,
         2291737,      588]))

In [21]:
def c_anist_cost(i, j, x, y, mu = 10, wt = 2):

    mu_sqr = mu * mu
    h_diff = dem_data[i][j] - dem_data[x][y]
    h_sqr = h_diff * h_diff
    c_dv = (mask_data[i][j] + mask_data[x][y]) / 2
    cst = np.sqrt(mu_sqr + h_sqr) * (c_dv + math.atan(h_diff / mu) * wt) + distance_matrix[i][j]

    return cst

In [56]:
def get_neigh_cost(i, j):
    arr = []

    #(1) col - 1, row - 1
    if (j - 1 >= 0) and (i - 1 >= 0):
        if (distance_matrix[i - 1][j - 1] > distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j - 1)):
            distance_matrix[i - 1][j - 1] = distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j - 1) 
            parent[i - 1][j - 1] = i, j
        arr.append([distance_matrix[i - 1][j - 1], [i - 1, j - 1], [i, j]])
    # else:
    #     arr.append(math.inf)
            
    
    #(2) col, row - 1
    if (i - 1 >= 0):
        if (distance_matrix[i - 1][j] > distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j)):
            distance_matrix[i - 1][j] = distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j)
            parent[i - 1][j] = i, j
        arr.append([distance_matrix[i - 1][j], [i - 1, j], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(3) col + 1, row - 1
    if (j + 1 < 8163) and (i - 1 >= 0):
        if (distance_matrix[i - 1][j + 1] > distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j + 1)):
            distance_matrix[i - 1][j + 1] = distance_matrix[i][j] + c_anist_cost(i, j, i - 1, j + 1)
            parent[i - 1][j + 1] = i, j
        arr.append([distance_matrix[i - 1][j + 1], [i - 1, j + 1], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(4) col - 1, row
    if (j - 1 >= 0):
        if (distance_matrix[i][j - 1] > distance_matrix[i][j] + c_anist_cost(i, j, i, j - 1)):
            distance_matrix[i][j - 1] = distance_matrix[i][j] + c_anist_cost(i, j, i, j - 1)
            parent[i][j - 1] = i, j
        arr.append([distance_matrix[i][j - 1], [i, j - 1], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(5) col + 1, row
    if (j + 1 < 8163):
        if (distance_matrix[i][j + 1] > distance_matrix[i][j] + c_anist_cost(i, j, i, j + 1)):
            distance_matrix[i][j + 1] = distance_matrix[i][j] + c_anist_cost(i, j, i, j + 1)
            parent[i][j + 1] = i, j
        arr.append([distance_matrix[i][j + 1], [i, j + 1], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(6) col - 1, row + 1
    if (j - 1 >= 0) and (i + 1 < 10500):
        if (distance_matrix[i + 1][j - 1] > distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j - 1)):
            distance_matrix[i + 1][j - 1] = distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j - 1)
            parent[i + 1][j - 1] = i, j
        arr.append([distance_matrix[i + 1][j - 1], [i + 1, j - 1], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(7) col, row + 1
    if (i + 1 < 10500):
        if (distance_matrix[i + 1][j] > distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j)):
            distance_matrix[i + 1][j] = distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j)
            parent[i + 1][j] = i, j
        arr.append([distance_matrix[i + 1][j], [i + 1, j], [i, j]])
    # else:
    #     arr.append(math.inf)
    
    #(8) col + 1, row + 1
    if (j + 1 < 8163) and (i + 1 < 10500):
        if (distance_matrix[i + 1][j + 1] > distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j + 1)):
            distance_matrix[i + 1][j + 1] = distance_matrix[i][j] + c_anist_cost(i, j, i + 1, j + 1)
            parent[i + 1][j + 1] = i, j
        arr.append([distance_matrix[i + 1][j + 1], [i + 1, j + 1], [i, j]])
    # else:
    #     arr.append(math.inf)

    return arr

In [57]:
dim = mask_data.shape
print(dim)

(10500, 8163)


In [124]:
start_pixel, end_pixel = [1770, 1442], [8344, 5485]
# start_pixel, end_pixel = [1770, 1442], [1900, 1700]
print(start_pixel, end_pixel)

[1770, 1442] [1900, 1700]


In [125]:
print(dem_data.shape, mask_data.shape)

(10500, 8163) (10500, 8163)


#### SPF Algorithm

In [126]:
from queue import Queue

distance_matrix = np.full((dim), math.inf)
inQueue = np.zeros((dim))
parent = np.full((dim), None)

i, j = start_pixel
parent[i][j] = [-1, -1]

i, j = start_pixel
distance_matrix[i][j] = 0
inQueue[i][j] = 1

Q = Queue()
Q.put(start_pixel)

# cnt = 10000 * 100
stop_flag = False
last = None

while not Q.empty():
    # if cnt == 0:
    #     break
    # cnt = cnt - 1

    if stop_flag:
        break 

    i, j = Q.get()
    last = [i, j]
    inQueue[i][j] = 0

    ngbors = get_neigh_cost(i, j)
    for n in ngbors:
        a, b = n[1]

        if a == end_pixel[0] and b == end_pixel[1]:
            stop_flag = True

        if inQueue[a][b]:
            continue
        inQueue[a][b] = 1
        Q.put(n[1])

In [127]:
print(distance_matrix[end_pixel[0]][end_pixel[1]])

2.4018682419038963e+81


In [128]:
!rm -rf path.txt

In [129]:
path = []
pr = parent[end_pixel[0]][end_pixel[1]]

# cnt = 15000
while (pr[0] != -1) and (pr[1] != -1):
    path.append(pr)
    # path.append('-')
    with open('path.txt', 'a') as f:
        f.write(str(pr) + '\n')

    # cnt = cnt - 1
    # if cnt == 0:
    #     break

    pr = parent[pr[0]][pr[1]]

In [130]:
path_list = []
with open('path.txt', 'r') as f:
    for point in f:
        path_list.append(point)

In [131]:
len(path_list)

258

In [132]:
point = path_list[0].replace('\n', '').split(' ')
pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])
print(pi, pj)

1899 1699


In [133]:
len(path_list)

258

In [134]:
path_list.reverse()

In [135]:
ordinates_dict = {}


for i in range(len(path_list)):
    point = path_list[i].replace('\n', '').split(' ')
    # print(point)
    pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])

    ext_i, ext_j = left + (pi * 10), top - (pj * 10)

    # ordinates_dict[(pi, pj)] = extent_matrix[pi][pj]
    ordinates_dict[pi, pj] = [ext_i, ext_j]

In [136]:
ordinates_dict
ordinates_list = []
for key, value in ordinates_dict.items():
    ordinates_list.append(value)

In [137]:
import shapefile
w = shapefile.Writer(f'/home/shrayank_mistry/Modules/project-mum-pune/routes-shape/shortest-path-faster/shapefiles/test/multipoint')
w.field('name', 'C')

w.multipoint(ordinates_list) 
w.record('multipoint1')

w.close()

In [138]:
road_lenght = 0
index = 1
for _ in ordinates_list[1:]:
    i, j = ordinates_list[index][0], ordinates_list[index][1]
    x, y = ordinates_list[index - 1][0], ordinates_list[index - 1][1]

    if (x - i == 10.0) and (y - j == -10.0):
        road_lenght += math.sqrt(2 * 100)
    else:
        road_lenght += 10 

In [139]:
print(f'Current Road-length = {road_lenght / 1000} kms')

Current Road-length = 2.57 kms
