In [99]:
import numpy as np
from osgeo import ogr, gdal, osr
import rasterio
import json


import matplotlib.pyplot as plt
import pandas as pd
import os.path
import re

#### Resize DEM from 30 to 10m

In [100]:
# Reading Normal DEM data
area_dem = '/home/shrayank_mistry/Modules/Area-routes/ASalem/dem_clipped.tif'
dem = rasterio.open(area_dem, count = 1)

dem = np.array(dem.read(1))
print(dem.shape)

(5337, 5036)


In [101]:
# Up-sampling DEM to 10m resolution
import rasterio
from rasterio.enums import Resampling

# whole-numbers indicate upscaling, fractions indicate downscaling
upscale_factor = 3


with rasterio.open('/home/shrayank_mistry/Modules/Area-routes/ASalem/dem_clipped.tif') as dataset:

    # resample data to target shape
    data = dataset.read(
        out_shape=(
            dataset.count,
            int(dataset.height * upscale_factor),
            int(dataset.width * upscale_factor)
        ),
        resampling=Resampling.bilinear
    )

    # scale image transform
    transform = dataset.transform * dataset.transform.scale(
        (dataset.width / data.shape[-1]),
        (dataset.height / data.shape[-2])
    )

In [102]:
dem = data[0]
print(dem.shape)

(16011, 15108)


In [103]:
# reading LULC data
area_cover = '/home/shrayank_mistry/Modules/Area-routes/ASalem/mask.tif'
area = rasterio.open(area_cover, count = 1)

area = np.array(area.read(1))

In [104]:
area.shape

(16233, 15043)

In [105]:
dem_data, mask_data = dem, area

print(dem_data.shape, mask_data.shape)
width, height = 15043, 16011

dem_data, mask_data = dem_data[:height,:width], mask_data[:height, :width]
print(dem_data.shape, mask_data.shape)

dem_data, mask_data = dem_data.T, mask_data.T
print(dem_data.shape, mask_data.shape)

(16011, 15108) (16233, 15043)
(16011, 15043) (16011, 15043)
(15043, 16011) (15043, 16011)


In [106]:
np.unique(mask_data, return_counts = True)

(array([-999,    0,    1,    2,    3,    4,    5,    6,    7], dtype=int16),
 array([      12,        6,  7691351, 45743885,  7449758, 75677893,
        12328163, 47330872, 44631533]))

#### AHP Mapping

In [107]:
ahp_map = {

'urban': 0.29,
'farms': 0.239,
'dense-forest': 0.207,
'water': 0.13,
'fallow': 0.067,
'sparse-forest': 0.049,
'barren-land': 0.019,
'unclassified':7,
'unclassified2': 8,

}

class_map = {
    -999: 'unclassified2',
    0: 'unclassified',
    1: 'water',
    2: 'dense-forest',
    3: 'sparse-forest',
    4: 'barren-land',
    5: 'urban',
    6: 'farms',
    7: 'fallow',

}

In [108]:
# Helper function to map from LULC to class-map to ahp values
def set_weights(c):
    c_str = class_map.get(c)
    return ahp_map[c_str]

In [109]:
set_weights_vtr = np.vectorize(set_weights)
mask_data = set_weights_vtr(mask_data)

In [110]:
np.unique(mask_data, return_counts = True)

(array([0.019, 0.049, 0.067, 0.13 , 0.207, 0.239, 0.29 , 7.   , 8.   ]),
 array([75677893,  7449758, 44631533,  7691351, 45743885, 47330872,
        12328163,        6,       12]))

#### Start-End Co-ordinates

In [111]:
# ----------------------------- source_shp -------------------------------- #

file = ogr.Open("/home/shrayank_mistry/Modules/Area-routes/ASalem/source/source.shp")
source_shp = file.GetLayer(0)

feature = source_shp.GetFeature(0)
source_shp = feature.ExportToJson()

source_shp = json.loads(source_shp)
start_ext = source_shp['geometry']['coordinates']

# ----------------------------- destination_shp -------------------------------- #

file = ogr.Open("/home/shrayank_mistry/Modules/Area-routes/ASalem/destination/destination.shp")
destination_shp = file.GetLayer(0)

feature = destination_shp.GetFeature(0)
destination_shp = feature.ExportToJson()

destination_shp = json.loads(destination_shp)
end_ext = destination_shp['geometry']['coordinates']

In [112]:
print(start_ext, end_ext) 

[892086.4271144224, 1402194.1872975053] [849204.4494360032, 1290500.4032451797]


#### Raster Co-ordinates (Left, Bottom, Right, Top)

In [113]:
path = '/home/shrayank_mistry/Modules/Area-routes/ASalem/raster.tif' 

data = rasterio.open(path)
print(data.bounds)

extent = data.bounds

left, bottom, right, top = extent[0], extent[1], extent[2], extent[3]
print(left, bottom, right, top)

BoundingBox(left=807951.0194687467, bottom=1255157.4422908756, right=958381.0194687467, top=1417487.4422908756)
807951.0194687467 1255157.4422908756 958381.0194687467 1417487.4422908756


In [114]:
width = round(right - left)
height = round(top - bottom)

print("Height and Width of Raster")
print(height, width)

Height and Width of Raster
162330 150430


### Finding pixels of start-point and end-point from extents

In [115]:
# # [Do not run - already avaliable]
# # start_pixel, end_pixel = [14424, 17699], [54850, 83443]
# start_pixel, end_pixel = [0, 0], [0, 0]
# start_flag, end_flag = True, True

# for i in range(height):
#     for j in range(width):

#         if (not start_flag) and (not end_flag):
#             break
        
#         # print(round(left + j), round(top - i))
#         if (start_flag and ((round(left + j)) == round(start_ext[0])) and ((round(top - i)) == round(start_ext[1]))):
#             start_pixel = [i, j]
#             start_flag = False

        
#         if (end_flag and ((round(left + j)) == round(end_ext[0])) and ((round(top - i)) == round(end_ext[1]))):
#             end_pixel = [i, j]
#             end_flag = False

KeyboardInterrupt: 

In [ ]:
# start_pixel, end_pixel

([15293, 84135], [126987, 41253])

In [116]:
start_pixel, end_pixel = [15293, 84135], [126987, 41253]

In [117]:
start_pixel = np.array(start_pixel)
start_pixel = start_pixel / 10

start_pixel = list(np.rint(start_pixel))
start_pixel = list(np.array(start_pixel, dtype = 'int'))

end_pixel = np.array(end_pixel)
end_pixel = end_pixel / 10

end_pixel = list(np.rint(end_pixel))
end_pixel = list(np.array(end_pixel, dtype = 'int'))

In [118]:
print(start_pixel, end_pixel)
# start_pixel, end_pixel = [1770, 1442], [8344, 5485]
# print(start_pixel, end_pixel)

[1529, 8414] [12699, 4125]


#### A* search algorithm

In [119]:
def condition_check(start, end):
    if (start[0] == end[0]) and (start[1] == end[1]):
        return False
    return True

In [120]:
import math
from queue import PriorityQueue

In [121]:
mask_data = mask_data * 5000

In [122]:
np.unique(mask_data, return_counts = True)

(array([   95.,   245.,   335.,   650.,  1035.,  1195.,  1450., 35000.,
        40000.]),
 array([75677893,  7449758, 44631533,  7691351, 45743885, 47330872,
        12328163,        6,       12]))

In [123]:
def c_anist_cost(i, j, x, y, mu = 10, wt = 2):

    mu_sqr = mu * mu
    h_diff = dem_data[i][j] - dem_data[x][y]
    h_sqr = h_diff * h_diff
    c_dv = (mask_data[i][j] + mask_data[x][y]) / 2
    cst = np.sqrt(mu_sqr + h_sqr) * (c_dv + math.atan(h_diff / mu) * wt) + acc_cost[i][j]

    return cst

In [124]:
# Manhattan Distance
def h_cost_manhattan(i, j):
    xa, ya, xb, yb = end_pixel[0], end_pixel[1], i, j
    return abs(xa - xb) + abs(ya - yb)

# Euclidean Distance
def h_cost_euclidean(i, j):
    xa, ya, xb, yb = end_pixel[0], end_pixel[1], i, j
    return math.sqrt((xa - xb) ** 2 + (ya - yb) ** 2)

# Diagonal Distance
def h_cost_diagonal(i, j):
    xa, ya, xb, yb = end_pixel[0], end_pixel[1], i, j
    return abs(xa - xb) + abs(ya - yb) + (math.sqrt(2) - 2) * min(abs(xa - xb), abs(ya - yb))

# Chebyshev Distance
def h_cost_chebyshev(i, j):
    xa, ya, xb, yb = end_pixel[0], end_pixel[1], i, j
    return max(abs(xa - xb), abs(ya - yb))

# New-heuristic function
def h_cost_new(i, j):
    xa, ya, xb, yb = end_pixel[0], end_pixel[1], i, j
    return h_cost_euclidean(i, j) + h_cost_chebyshev(i, j) * 2

In [125]:
heuristic_dict = {
    1: h_cost_manhattan,
    2: h_cost_euclidean,
    3: h_cost_diagonal,
    4: h_cost_chebyshev,
    5: h_cost_new
}

In [126]:
def get_neigh_cost(i, j, flag):
    arr = []

    heuristic_func = heuristic_dict.get(flag)


    #(1) col - 1, row - 1
    if (j - 1 >= 0) and (i - 1 >= 0):
        g = c_anist_cost(i, j, i - 1, j - 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i - 1][j - 1] > (g + h)):
            parent[i - 1][j - 1] = i, j
            acc_cost[i - 1][j - 1] = (g + h)
        arr.append([acc_cost[i - 1][j - 1], [i - 1, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(2) col, row - 1
    if (i - 1 >= 0):
        g = c_anist_cost(i, j, i - 1, j)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i - 1][j] > (g + h)):
            parent[i - 1][j] = i, j
            acc_cost[i - 1][j] = (g + h)
        arr.append([acc_cost[i - 1][j], [i - 1, j], [i, j]])
    else:
        arr.append(math.inf)

    #(3) col + 1, row - 1
    if (j + 1 < 8163) and (i - 1 >= 0):
        g = c_anist_cost(i, j, i - 1, j + 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i - 1][j + 1] > (g + h)):
            parent[i - 1][j + 1] = i, j
            acc_cost[i - 1][j + 1] = (g + h)
        arr.append([acc_cost[i - 1][j + 1], [i - 1, j + 1], [i, j]])
    else:
        arr.append(math.inf)

    #(4) col - 1, row
    if (j - 1 >= 0):
        g = c_anist_cost(i, j, i, j - 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i][j - 1] > (g + h)):
            parent[i][j - 1] = i, j
            acc_cost[i][j - 1] = (g + h)
        arr.append([acc_cost[i][j - 1], [i, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(5) col + 1, row
    if (j + 1 < 8163):
        g = c_anist_cost(i, j, i, j + 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i][j + 1] > (g + h)):
            parent[i][j + 1] = i, j
            acc_cost[i][j + 1] = (g + h)
        arr.append([acc_cost[i][j + 1], [i, j + 1], [i, j]])
    else:
        arr.append(math.inf)

    #(6) col - 1, row + 1
    if (j - 1 >= 0) and (i + 1 < 10500):
        g = c_anist_cost(i, j, i + 1, j - 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i + 1][j - 1] > (g + h)):
            parent[i + 1][j - 1] = i, j
            acc_cost[i + 1][j - 1] = (g + h)
        arr.append([acc_cost[i + 1][j - 1], [i + 1, j - 1], [i, j]])
    else:
        arr.append(math.inf)

    #(7) col, row + 1
    if (i + 1 < 10500):
        g = c_anist_cost(i, j, i + 1, j)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i + 1][j] > (g + h)):
            parent[i + 1][j] = i, j
            acc_cost[i + 1][j] = (g + h)
        arr.append([acc_cost[i + 1][j], [i + 1, j], [i, j]])
    else:
        arr.append(math.inf)

    #(8) col + 1, row + 1
    if (j + 1 < 8163) and (i + 1 < 10500):
        g = c_anist_cost(i, j, i + 1, j + 1)
        h = heuristic_func(i - 1, j - 1)

        if (acc_cost[i + 1][j + 1] > (g + h)):
            parent[i + 1][j + 1] = i, j
            acc_cost[i + 1][j + 1] = (g + h)
        arr.append([acc_cost[i + 1][j + 1], [i + 1, j + 1], [i, j]])
    else:
        arr.append(math.inf)
    

    return arr

In [127]:
end_pixel

[12699, 4125]

In [128]:
dim = mask_data.shape
print(dim)

(15043, 16011)


In [129]:
# start_pixel, end_pixel = [1770, 1442], [8344, 5485]
# start_pixel, end_pixel = [1770, 1442], [1980, 1600]
print(start_pixel, end_pixel)

[1529, 8414] [12699, 4125]


### Heuristic Check Flag Setting
#### 1. Manhattan
#### 2. Euclidean
#### 3. Diagonal distance heuristic function
#### 4. Chebyshev distance heuristic function
#### 5. new heuristic function

In [ ]:
FLAG = 5
import os
import shapefile

route_paths = {
    1: 'a-star-man',
    2: 'a-star-euc',
    3: 'a-star-diag',
    4: 'a-star-chesb',
    5: 'a-star-new',
}

for f in range(1, 6):

    FLAG = f
    # A* main   
    #--------------------#####----------------------#
    Q = PriorityQueue()
    s_pixel, e_pixel = start_pixel, end_pixel

    # mask_copy.shape, dem_data.shape

    visited = np.zeros((dim))
    acc_cost = np.full((dim), math.inf)

    acc_cost[s_pixel[0]][s_pixel[1]] = 0
    visited[s_pixel[0]][s_pixel[1]] = 1

    parent = np.full((dim), None)
    parent[s_pixel[0]][s_pixel[1]] = -1, -1

    while (condition_check(s_pixel, e_pixel)):
    
        i, j = s_pixel
        # h-cost(0) - indicates Euclidean distance
        # h-cost(1) - indicates Manhattan distance

        neighbours_cost = get_neigh_cost(i, j, FLAG)
        for nc in neighbours_cost:
            if nc == math.inf:
                continue
            else:
                Q.put(nc)
        
        bst = Q.get()
        m, n = bst[1][0], bst[1][1]

        while True:
            if visited[m][n] == 0:
                break
            bst = Q.get()
            m, n = bst[1][0], bst[1][1]

        # set-visited
        visited[m][n] = 1
        # path.append([m, n])
        # print(m, n)

        parent[m][n] = bst[2][0], bst[2][1]

        s_pixel = [m, n]
    #--------------------#####----------------------#
    # -- Path saving code
    #--------------------#####----------------------#
    print(acc_cost[end_pixel[0]][end_pixel[1]])

    os.mkdir(f'paths/P{FLAG}')
    # !mkdir f'paths/P{FLAG}'
    
    path = []
    pr = parent[end_pixel[0]][end_pixel[1]]

    # cnt = 15000
    while (pr[0] != -1) and (pr[1] != -1):
        path.append(pr)
        # path.append('-')
        with open(f'paths/P{FLAG}/path.txt', 'a') as f:
            f.write(str(pr) + '\n')

        # cnt = cnt - 1
        # if cnt == 0:
        #     break

        pr = parent[pr[0]][pr[1]]
    
    path_list = []
    with open(f'paths/P{FLAG}/path.txt', 'r') as f:
        for point in f:
            path_list.append(point)
    
    path_list.reverse()
    ordinates_dict = {}

    for i in range(len(path_list)):
        point = path_list[i].replace('\n', '').split(' ')
        pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])

        ext_i, ext_j = left + (pi * 10), top - (pj * 10)

        # ordinates_dict[(pi, pj)] = extent_matrix[pi][pj]
        ordinates_dict[pi, pj] = [ext_i, ext_j]
    
    # ordinates_dict
    ordinates_list = []
    for key, value in ordinates_dict.items():
        ordinates_list.append(value)
    
    # import shapefile
    w = shapefile.Writer(f'/home/shrayank_mistry/Modules/Area-routes/ASalem/routes-shape/{route_paths[FLAG]}/shapefiles/test/multipoint')
    w.field('name', 'C')

    w.multipoint(ordinates_list) 
    w.record('multipoint1')

    w.close()

    road_lenght = 0
    index = 1
    for _ in ordinates_list[1:]:
        i, j = ordinates_list[index][0], ordinates_list[index][1]
        x, y = ordinates_list[index - 1][0], ordinates_list[index - 1][1]

        if (x - i == 10.0) and (y - j == -10.0):
            road_lenght += math.sqrt(2 * 100)
        else:
            road_lenght += 10 

    print(f'Current Road-length = {road_lenght / 1000} kms')
    #--------------------#####----------------------#

    

In [ ]:
Q = PriorityQueue()
s_pixel, e_pixel = start_pixel, end_pixel

# mask_copy.shape, dem_data.shape

visited = np.zeros((dim))
acc_cost = np.full((dim), math.inf)

acc_cost[s_pixel[0]][s_pixel[1]] = 0
visited[s_pixel[0]][s_pixel[1]] = 1

parent = np.full((dim), None)
parent[s_pixel[0]][s_pixel[1]] = -1, -1

while (condition_check(s_pixel, e_pixel)):
    
    i, j = s_pixel
    # h-cost(0) - indicates Euclidean distance
    # h-cost(1) - indicates Manhattan distance

    neighbours_cost = get_neigh_cost(i, j, FLAG)
    for nc in neighbours_cost:
        if nc == math.inf:
            continue
        else:
            Q.put(nc)
    
    bst = Q.get()
    m, n = bst[1][0], bst[1][1]

    while True:
        if visited[m][n] == 0:
            break
        bst = Q.get()
        m, n = bst[1][0], bst[1][1]

    # set-visited
    visited[m][n] = 1
    # path.append([m, n])
    # print(m, n)

    parent[m][n] = bst[2][0], bst[2][1]

    s_pixel = [m, n]

In [ ]:
print(acc_cost[end_pixel[0]][end_pixel[1]])

66997309.37078367


In [ ]:
!rm -rf path.txt

In [ ]:
!mkdir f'paths/P{FLAG}'

In [ ]:
path = []
pr = parent[end_pixel[0]][end_pixel[1]]

# cnt = 15000
while (pr[0] != -1) and (pr[1] != -1):
    path.append(pr)
    # path.append('-')
    with open(f'paths/P{FLAG}/path.txt', 'a') as f:
        f.write(str(pr) + '\n')

    # cnt = cnt - 1
    # if cnt == 0:
    #     break

    pr = parent[pr[0]][pr[1]]

In [ ]:
path_list = []
with open(f'paths/P{FLAG}/path.txt', 'r') as f:
    for point in f:
        path_list.append(point)

In [ ]:
len(path_list)

6787

In [ ]:
point = path_list[0].replace('\n', '').split(' ')
pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])
print(pi, pj)

8343 5484


In [ ]:
len(path_list)

6787

In [ ]:
path_list.reverse()

In [ ]:
%%time
ordinates_dict = {}


for i in range(len(path_list)):
    point = path_list[i].replace('\n', '').split(' ')
    pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])

    ext_i, ext_j = left + (pi * 10), top - (pj * 10)

    # ordinates_dict[(pi, pj)] = extent_matrix[pi][pj]
    ordinates_dict[pi, pj] = [ext_i, ext_j]

CPU times: user 42.8 ms, sys: 28 ms, total: 70.8 ms
Wall time: 70.4 ms


In [ ]:
ordinates_dict
ordinates_list = []
for key, value in ordinates_dict.items():
    ordinates_list.append(value)

### Heuristic Check Flag Setting
#### 1. Manhattan
#### 2. Euclidean
#### 3. Diagonal distance heuristic function
#### 4. Chebyshev distance heuristic function
#### 5. new heuristic function

In [ ]:
route_paths = {
    1: 'a-star-man',
    2: 'a-star-euc',
    3: 'a-star-diag',
    4: 'a-star-chesb',
    5: 'a-star-new',
}

In [ ]:
import shapefile
w = shapefile.Writer(f'/home/shrayank_mistry/Modules/Area-routes/ASalem/routes-shape/{route_paths[FLAG]}/shapefiles/test/multipoint')
w.field('name', 'C')

w.multipoint(ordinates_list) 
w.record('multipoint1')

w.close()

In [ ]:
road_lenght = 0
index = 1
for _ in ordinates_list[1:]:
    i, j = ordinates_list[index][0], ordinates_list[index][1]
    x, y = ordinates_list[index - 1][0], ordinates_list[index - 1][1]

    if (x - i == 10.0) and (y - j == -10.0):
        road_lenght += math.sqrt(2 * 100)
    else:
        road_lenght += 10 

print(f'Current Road-length = {road_lenght / 1000} kms')

In [ ]:
print(f'Current Road-length = {road_lenght / 1000} kms')

Current Road-length = 95.96853234263206 kms


#### Co-ordinates to Pixel Mapping

In [ ]:
# %%time
# pixels_dict = {}


# for i in range(len(path_list)):
#     point = path_list[i].replace('\n', '').split(' ')
#     pi, pj = int(point[0].split(',')[0].split('(')[1]), int(point[1].split(',')[0].split(')')[0])

#     ext_i, ext_j = left + (pi * 10), top - (pj * 10)

#     # ordinates_dict[(pi, pj)] = extent_matrix[pi][pj]
#     # ordinates_dict[pi, pj] = [ext_i, ext_j]
#     pixels_dict[ext_i, ext_j] = [pi, pj]

CPU times: user 216 ms, sys: 8 ms, total: 224 ms
Wall time: 228 ms


In [ ]:
# # reading LULC data
# area_cover = '/home/shrayank_mistry/Modules/project-mum-pune/mask.tif'
# area = rasterio.open(area_cover, count = 1)

# area = np.array(area.read(1))

# dem_data, mask_data = dem, area

# print(dem_data.shape, mask_data.shape)
# width, height = 10500, 8163

# dem_data, mask_data = dem_data[:height,:width], mask_data[:height, :width]
# print(dem_data.shape, mask_data.shape)

# dem_data, mask_data = dem_data.T, mask_data.T
# print(dem_data.shape, mask_data.shape)

(8163, 10830) (8273, 10500)
(8163, 10500) (8163, 10500)
(10500, 8163) (10500, 8163)


In [ ]:
# check_pixels = {
#     1: 0,
#     2: 0,
#     3: 0,
#     4: 0,
#     5: 0,
#     6: 0,
#     7: 0,
# }


In [ ]:
# r = shapefile.Reader(f'/home/shrayank_mistry/Modules/project-mum-pune/routes-shape/{route_paths[FLAG]}/shapefiles/test/multipoint.shp')
# feature = r.shapeRecords()[0]
# first = feature.shape.__geo_interface__  

In [ ]:
# total_pxs = len(first['coordinates'])
# for cord in first['coordinates']:
#     pi, pj = pixels_dict[cord]
#     cs = mask_data[pi][pj]

#     check_pixels[cs] += 1

In [ ]:
# check_pixels

{1: 593, 2: 502, 3: 1541, 4: 2075, 5: 263, 6: 179, 7: 2445}

#### Percentage Calculation

In [ ]:
# for key, value in check_pixels.items():
#     check_pixels[key] = np.round(((value / total_pxs) * 100), 2)

In [ ]:
# check_pixels

{1: 7.8, 2: 6.61, 3: 20.28, 4: 27.31, 5: 3.46, 6: 2.36, 7: 32.18}

In [ ]:
# classes = {1 : 'Water', 2: 'Dense-forest', 3: 'Sparse-forest', 4: 'Barren-land', 5: 'Urban-land', 6: 'Farmland', 7: 'Fallowland'}
# df_dict_perc = {}
# for key, value in check_pixels.items():
#     df_dict_perc[classes[key]] = f'{check_pixels[key]}%'


In [ ]:
# df_dict_perc

{'Water': '7.8%',
 'Dense-forest': '6.61%',
 'Sparse-forest': '20.28%',
 'Barren-land': '27.31%',
 'Urban-land': '3.46%',
 'Farmland': '2.36%',
 'Fallowland': '32.18%'}

In [ ]:
# print(f'Current Road-length = {road_lenght / 1000} kms')

Current Road-length = 75.97 kms


In [ ]:
# road_distance = road_lenght / 1000
# road_distance

75.97

In [ ]:
# df_dict_dist = {}
# recheck = 0
# for key, value in check_pixels.items():
#     df_dict_dist[classes[key]] = (check_pixels[key] * road_distance) / 100
#     recheck += (check_pixels[key] * road_distance) / 100

In [ ]:
# df_dict_dist

{'Water': 5.925660000000001,
 'Dense-forest': 5.021617,
 'Sparse-forest': 15.406716000000001,
 'Barren-land': 20.747407,
 'Urban-land': 2.628562,
 'Farmland': 1.792892,
 'Fallowland': 24.447145999999996}

In [ ]:
# recheck

75.97